import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

// Define the styles for the PDF
const styles = StyleSheet.create({
  page: {
    padding: 20,
    fontFamily: "Helvetica",
  },
  header: {
    textAlign: "center",
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 20,
  },
  courseContainer: {
    marginBottom: 10,
  },
  courseTitle: {
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 4,
  },
  sectionContainer: {
    marginBottom: 6,
  },
  section: {
    fontSize: 12,
  },
  footer: {
    marginTop: 20,
    fontSize: 10,
    textAlign: "center",
    color: "#777",
  },
});

const TimetablePDF = ({ registeredCourses }) => {
  return (
    <Document>
      <Page style={styles.page}>
        <Text style={styles.header}>Class Schedule</Text>
        <View>
          {registeredCourses.length === 0 ? (
            <Text>No courses selected.</Text>
          ) : (
            registeredCourses.map((course, index) => (
              <View key={index} style={styles.courseContainer}>
                <Text style={styles.courseTitle}>{course.name}</Text>
                <View style={styles.sectionContainer}>
                  {course.section ? (
                    <Text style={styles.section}>Section: {course.section}</Text>
                  ) : (
                    <Text style={styles.section}>No section selected</Text>
                  )}
                </View>
              </View>
            ))
          )}
        </View>
        <Text style={styles.footer}>Generated by Course Registration System</Text>
      </Page>
    </Document>
  );
};

export default TimetablePDF;
